export const answers = [
  //а
  { word: "агронОмія", description: "" },
  { word: "алфАвІт", description: "" },
  { word: "Аркушик", description: "" },
  { word: "асиметрІя", description: "" },
  //б
  { word: "багаторазОвий", description: "" },
  { word: "безпринцИпний", description: "" },
  { word: "бЕшкет", description: "" },
  { word: "блАговіст", description: "" },
  { word: "близькИй", description: "" },
  { word: "болотИстий", description: "" },
  { word: "борОдавка", description: "" },
  { word: "босОніж", description: "" },
  { word: "боЯзнь", description: "" },
  { word: "бурштинОвий", description: "" },
  { word: "бюлетЕнь", description: "" },
  //в
  { word: "вАги", description: "у множині" },
  { word: "вантажІвка", description: "" },
  { word: "веснЯнИй", description: "" },
  { word: "вИгода", description: "користь" },
  { word: "вигОда", description: "зручність" },
  { word: "видАння", description: "" },
  { word: "визвОльний", description: "" },
  { word: "вимОга", description: "" },
  { word: "вИпадок", description: "" },
  { word: "вирАзний", description: "" },
  { word: "вИсіти", description: "" },
  { word: "вИтрата", description: "" },
  { word: "вишИваний", description: "" },
  { word: "відвезтИ", description: "" },
  { word: "відвестИ", description: "" },
  { word: "вІдгомін", description: "" },
  { word: "віднестИ", description: "" },
  { word: "вІдомість", description: "список" },
  { word: "відОмість", description: "повідомлення, дані, популярність" },
  { word: "вІрші", description: "" },
  { word: "віршовИй", description: "" },
  { word: "вітчИм", description: "" },
  //г
  { word: "гальмО", description: "" },
  { word: "гАльма", description: "" },
  { word: "глядАч", description: "" },
  { word: "горошИна", description: "" },
  { word: "граблІ", description: "" },
  { word: "гуртОжиток", description: "" },
  //д
  { word: "данИна", description: "" },
  { word: "дАно", description: "" },
  { word: "децимЕтр", description: "" },
  { word: "дЕщиця", description: "" },
  { word: "де-Юре", description: "" },
  { word: "джерелО", description: "" },
  { word: "дИвлячись", description: "" },
  { word: "дичАвіти", description: "" },
  { word: "діалОг", description: "" },
  { word: "добовИй", description: "" },
  { word: "добУток", description: "" },
  { word: "довезтИ", description: "" },
  { word: "довестИ", description: "" },
  { word: "довІдник", description: "" },
  { word: "дОгмат", description: "" },
  { word: "донестИ", description: "" },
  { word: "дОнька", description: "" },
  { word: "дочкА", description: "" },
  { word: "дрОва", description: "" },
  //е
  { word: "експЕрт", description: "" },
  //є
  { word: "єретИк", description: "" },
  //ж
  { word: "жалюзІ", description: "" },
  //з
  { word: "завдАння", description: "" },
  { word: "завезтИ", description: "" },
  { word: "завестИ", description: "" },
  { word: "зАвжди", description: "" },
  { word: "завчасУ", description: "" },
  { word: "зАгадка", description: "" },
  { word: "заіржАвілий", description: "" },
  { word: "заіржАвіти", description: "" },
  { word: "закінчИти", description: "" },
  { word: "зАкладка", description: "у книзі" },
  { word: "зАкрутка", description: "" },
  { word: "залишИти", description: "" },
  { word: "замІжня", description: "" },
  { word: "занестИ", description: "" },
  { word: "зАпонка", description: "" },
  { word: "заробІток", description: "" },
  { word: "зАставка", description: "" },
  { word: "зАстібка", description: "" },
  { word: "застОпорити", description: "" },
  { word: "звИсока", description: "" },
  { word: "здАлека", description: "" },
  { word: "зібрАння", description: "" },
  { word: "зобразИти", description: "" },
  { word: "зОзла", description: "" },
  { word: "зрАння", description: "" },
  { word: "зрУчний", description: "" },
  { word: "зубОжіння", description: "" },
  //і
  { word: "індУстрія", description: "" },
  //к
  { word: "кАмбала", description: "" },
  { word: "каталОг", description: "" },
  { word: "квартАл", description: "" },
  { word: "кИшка", description: "" },
  { word: "кіломЕтр", description: "" },
  { word: "кінчИти", description: "" },
  { word: "кОлесо", description: "" },
  { word: "кОлія", description: "" },
  { word: "кОпчений", description: "дієприкметник" },
  { word: "копчЕний", description: "прикметник" },
  { word: "корИсний", description: "" },
  { word: "кОсий", description: "" },
  { word: "котрИй", description: "" },
  { word: "крицЕвий", description: "" },
  { word: "крОїти", description: "" },
  { word: "кропивА", description: "" },
  { word: "кулінАрія", description: "" },
  { word: "кУрятина", description: "" },
  //л
  { word: "лАте", description: "" },
  { word: "листопАд", description: "" },
  { word: "літОпис", description: "" },
  { word: "лЮстро", description: "" },
  //м
  { word: "мАбУть", description: "" },
  { word: "магістЕрський", description: "" },
  { word: "мАркетинг", description: "" },
  { word: "мерЕжа", description: "" },
  { word: "металУргія", description: "" },
  { word: "мілімЕтр", description: "" },
  //н
  { word: "навчАння", description: "" },
  { word: "нанестИ", description: "" },
  { word: "напІй", description: "" },
  { word: "нАскрізний", description: "" },
  { word: "нАчинка", description: "" },
  { word: "ненАвидіти", description: "" },
  { word: "ненАвисний", description: "" },
  { word: "ненАвисть", description: "" },
  { word: "нестИ", description: "" },
  { word: "нІздря", description: "" },
  { word: "новИй", description: "" },
  //о
  { word: "обіцЯнка", description: "" },
  { word: "обрАння", description: "" },
  { word: "обрУч", description: "іменник" },
  { word: "одинАдцять", description: "" },
  { word: "одноразОвий", description: "" },
  { word: "ознАка", description: "" },
  { word: "Олень", description: "" },
  { word: "оптОвий", description: "" },
  { word: "осетЕр", description: "" },
  { word: "отАман", description: "" },
  { word: "Оцет", description: "" },
  //п
  { word: "павИч", description: "" },
  { word: "партЕр", description: "" },
  { word: "пЕкарський", description: "" },
  { word: "перевезтИ", description: "" },
  { word: "перевестИ", description: "" },
  { word: "перЕкис", description: "" },
  { word: "перелЯк", description: "" },
  { word: "перенестИ", description: "" },
  { word: "перЕпад", description: "" },
  { word: "перЕпис", description: "" },
  { word: "піалА", description: "" },
  { word: "пІдданий", description: "дієприкметник" },
  { word: "піддАний", description: "іменник, істота" },
  { word: "пІдлітковий", description: "" },
  { word: "пізнАння", description: "" },
  { word: "пітнИй", description: "" },
  { word: "піцЕрія", description: "" },
  { word: "пОдруга", description: "" },
  { word: "пОзначка", description: "" },
  { word: "пОмилка", description: "" },
  { word: "помІщик", description: "" },
  { word: "помОвчати", description: "" },
  { word: "понЯття", description: "" },
  { word: "порядкОвий", description: "" },
  { word: "посерЕдині", description: "" },
  { word: "привезтИ", description: "" },
  { word: "привестИ", description: "" },
  { word: "прИморозок", description: "" },
  { word: "принестИ", description: "" },
  { word: "прИчіп", description: "" },
  { word: "прОділ", description: "" },
  { word: "промІжок", description: "" },
  { word: "псевдонІм", description: "" },
  //р
  { word: "рАзом", description: "" },
  { word: "рЕмінь", description: "пояс" },
  { word: "рЕшето", description: "" },
  { word: "рИнковий", description: "" },
  { word: "рівнИна", description: "" },
  { word: "роздрібнИй", description: "" },
  { word: "рОзпірка", description: "" },
  { word: "рукОпис", description: "" },
  { word: "руслО", description: "" },
  //с
  { word: "сантимЕтр", description: "" },
  { word: "свЕрдло", description: "" },
  { word: "серЕдина", description: "" },
  { word: "сЕча", description: "" },
  { word: "симетрІя", description: "" },
  { word: "сільськогосподАрський", description: "" },
  { word: "сімдесЯт", description: "" },
  { word: "слИна", description: "" },
  { word: "соломИнка", description: "" },
  { word: "стАтуя", description: "" },
  { word: "стовідсОтковий", description: "" },
  { word: "стрибАти", description: "" },
  //т
  { word: "текстовИй", description: "" },
  { word: "течіЯ", description: "" },
  { word: "тИгровий", description: "" },
  { word: "тисОвий", description: "" },
  { word: "тім’янИй", description: "" },
  { word: "травестІя", description: "" },
  { word: "тризУб", description: "" },
  { word: "тУлуб", description: "" },
  //у
  { word: "украЇнський", description: "" },
  { word: "уподОбання", description: "" },
  { word: "урочИстий", description: "" },
  { word: "усерЕдині", description: "" },
  //ф
  { word: "фартУх", description: "" },
  { word: "фаховИй", description: "" },
  { word: "фенОмен", description: "" },
  { word: "фОльга", description: "" },
  { word: "фОрзац", description: "" },
  //х
  { word: "хАос", description: "у міфології: стихія" },
  { word: "хаОс", description: "безлад" },
  //ц
  { word: "цАрина", description: "" },
  { word: "цемЕнт", description: "" },
  { word: "цЕнтнер", description: "" },
  { word: "ціннИк", description: "" },
  //ч
  { word: "чарівнИй", description: "" },
  { word: "черговИй", description: "" },
  { word: "читАння", description: "" },
  { word: "чорнОзем", description: "" },
  { word: "чорнОслив", description: "" },
  { word: "чотирнАдцять", description: "" },
  //ш
  { word: "шляхопровІд", description: "" },
  { word: "шовкОвий", description: "" },
  { word: "шофЕр", description: "" },
  //щ
  { word: "щЕлепа", description: "" },
  { word: "щИпці", description: "" },
  { word: "щодобовИй", description: "" },
  //я
  { word: "ярмаркОвий", description: "" }
];